- 30 days of code( c++)/day0.cpp
- 30 days of code( c++)/day1.cpp
> Resolved Errors #0, #1

- 30 days of code( c++)/day2.cpp
- 30 days of code( c++)/day3.cpp
- 30 days of code( c++)/day4.cpp
- 30 days of code( c++)/day5.cpp
- 30 days of code( c++)/day8.cpp
- 30 days of code( c++)/day9.cpp
Fixes issue #5  (compile error) and #9 (void problem in code)
> Day4&5 Issue

- 30 days of code( c++)/day12.cpp
- 30 days of code( c++)/day13.cpp
> Error in code resolved

- 30 days of code( c++)/day14.cpp
> Day 14 error fix

- 30 days of code( c++)/day15.cpp
> Day15 error fix

- 30 days of code( c++)/day22.cpp
> added day22.cpp

- 30 days of code( c++)/day19.cpp
> day19 challenge done

- 30 days of code( c++)/day23.cpp
> added day23.cpp

- CONTRIBUTING.md
I basically made a few corrections to the markdown
> Markdown Update

- 30 days of code( c++)/day17.cpp
> Added Day 17 (C++)

- 30 days of code( c++)/day24.cpp
> added day24.cpp

- 30 days of code( python)/day4.py
- 30 days of code( python)/day5.py
- 30 days of code( python)/day6.py
- 30 days of code( python)/day7.py
30 days of code (Day 4)  Hackerrank solution in Python3
> Day 4,5,6,7 solution in Python 3

- 30 days of code( c++)/day21.cpp
> Added day-21 in cpp

- 30 days of code( c++)/day26.cpp
Added Day 25: Running Time and Complexity Solution In CPP
> Added Day 26: Running Time and Complexity Solution In CPP

- CONTRIBUTING.md
- README.md
- Added `Note` in CONTRIBUTING.MD regarding inserting :white_check_mark: in the README.md against the language he/she has implemented. 
- Improved readability in README - #34
> Updated README, CONTRIBUTING

- 30 days of code( c++)/day18.cpp
Added the solution file to day 18 in cpp
> Added day18.cpp

- 30 days of code(c )/Day 0_ Hello, World.md
Kindly look in the layout and suggest will this layout work
your advice will help me to improve my future work
thanks
> Added Day 0 :Hello world in c language

- 30 days of code JAVA/day23.java
Added the solution file of day 23 in java
> Added Day 23: BST Level-Order Traversal

- 30 days of code( python)/day8.py
30 days of code hacerrank Day8 solution
> Added day 8 in python

- 30 days of code JAVA/day11.java
- 30 days of code JAVA/day12.java
> Solution for day 11

- 30 days of code JAVA/day22.java
- 30 days of code JAVA/day27.java
> day 22 and day 27

- 30 days of code JAVA/day5.java
- 30 days of code JAVA/day6.java
@rahulsain3000  merge this as well
> adding java day6 and day 5

- 30 days of code JAVA/day7.java
> adding day 7

- 30 days of code JAVA/day8.java
- 30 days of code JAVA/day9.java
> adding day8 and day9

- 30 days of code JAVA/day10.java
- 30 days of code JAVA/day13.java
- README.md
> adding day 10 and 13

- 30 days of code(c )/day29.c
@rahulsain3000 29Th day in C 😄
> adding day29 in C

- 30 days of code JAVA/day14.java
- 30 days of code JAVA/day16.java
- 30 days of code(c )/day15.c
@rahulsain3000  merge them please
> adding day14 15 and 16 in java and C

- 30 days of code JAVA/day17.java
- 30 days of code JAVA/day18.java
- 30 days of code(c )/day18.c
@rahulsain3000  this one please
> adding day 17 and 18

- 30 days of code(c )/Day 1.c
- 30 days of code(c )/Day 2.c
I have done Day 1 and 2 using C. The file extension is using '.c'. Checked the code in hackerrank its working fine.
> Day 1 and 2 using C

- 30 days of code JAVA/day21.java
- 30 days of code JAVA/day24.java
> day 23 and 24

- 30 days of code( python)/Day-11.py
Solution for day 11 problem using Python 🚀
> Day-11 solution in python

- 30 days of code JAVA/day25.java
@rahulsain3000 I think I am done 😆  🤣
> adding 25 day java

- 30 days of code JAVA/day20.java
- 30 days of code JAVA/day26.java
> Solution for day 20

- 30 days of code(c )/Day 3.c
- 30 days of code(c )/Day 7.c
> Added day 3.c and day 7.c

- README.md
add :white_check_mark: before creating PR
> Added Instuction to Readme

- 30 days of code(c )/Day_9_Recursion.c
Added Day - 9 Recursion 3 in C
> Day - 9 Recursion 3 in C

- 30 days of code( python)/day18.py
- 30 days of code( python)/day20.py
- 30 days of code( python)/day28.py
- 30 days of code( python)/day29.py
Added Python Implementation for 18th, 20th, 28th and 29th Day
Looking forward to get reviewed and merged soon ;)
> Add: Python Implementation for 18th, 20th, 28th and 29th Day

- 30 days of code(c )/Day_6_Lets_Review.c
Added Day - 6 Let's Review in C
> Added Day - 6 Let's Review in C

- 30 days of code( python)/day12.py
> day12 solution

- 30 days of code(c )/Day_9_Recursion.c
> Day 9_Recursion 3 in C

- 30 days of code(c )/day23.c
- 30 days of code(c )/day26.c
Solution of day 23 and day 26 in C
> Solution of day 23 and day 26 in C

- 30 days of code( python)/day14.py
- README.md
Checked the program on Hakerrank it is running fine. The output is correct.
> Day14 Python

- Hackerrank_30daysOFcode_in_JavaScript/day_14-Let_and_Const.js
**@rahulsain3000  please merge this**
> Create  day_14-Let_and_Const.js

- Hackerrank_30daysOFcode_C#/Day21.cs
@rahulsain3000  please review it and merge it if correct
> adding Day21 in C#

- Hackerrank_30daysOFcode_Go/day05.go
Solution of Problem 5 using Go
> Solution Day 5

- README.md
I added some correction to make your project attractive and clean. Please do not decline this, if you don't want to change my correction you drop this as usual, but please don't decline this. Please do not marked me as a spam also.
> Update README. (Add meaningful words)

- 30daysOFcode_C#/Day22.cs
**sample input:** 
**sample output:**
> added file : day22.cs

- 30daysOFcode_Go/day11.go
Added the answer for problem Day 11: 2D Array in go
> Answer for day 11 problem in go

- 30daysOFcode_C#/Day24.cs
> add file : Day24.cs

- 30daysOFcode_Go/day28.go
Solution for problem Day28: RegEx, Patterns, and Intro to Databases in Go
> Answer for day 28 problem in go

- 30daysOFcode_C#/Day26.cs
> added file : Day26.cs

- 30daysOFcode_Go/day23.go
Added solution for problem Day 23: BST Level-Order Traversal in go
> Answer for day 23 in go

- 30daysOFcode_C/Day4.c
Adding the Solution code in C of Day4 From 30daysofcode
> Added Solution of Day4 in C

- .gitignore
- 30daysOFcode_JavaScript/README.md
- 30daysOFcode_JavaScript/day_0-Hello_World.js
- 30daysOFcode_JavaScript/day_2-Operators.js
- 30daysOFcode_JavaScript/day_3-Conditional_Statements.js
- 30daysOFcode_JavaScript/day_5-Loops.js
- 30daysOFcode_JavaScript/package-lock.json
- 30daysOFcode_JavaScript/package.json
- 30daysOFcode_JavaScript/tests/day_0-Hello_World.test.js
- 30daysOFcode_JavaScript/tests/day_2-Operators.test.js
- 30daysOFcode_JavaScript/tests/day_3-Conditional_Statements.test.js
- 30daysOFcode_JavaScript/tests/day_5-Loops.test.js
Ref: #201 
This PR contains:
1. Configured **Jest** to enable testing.
2. Added **test cases** for 4 solutions 
3. Made the **code cleaner** for these 4 solutions.
4. Added a **REAMDE** file (for JS solutions) so that users can test their code using JEST and follow a convention.
Thanks
> Testing javascript solutions | Cleaned Code | Added Readme for JS folder

- 30daysOFcode_Go/day22.go
Solution for the problem Day 22: Binary Search Trees in go
> Answer for day 22 in go

- 30daysOFcode_Php/day0.php
- 30daysOFcode_Php/day1.php
- 30daysOFcode_Php/day3.php
- 30daysOFcode_Php/day4.php
- 30daysOFcode_Php/day5.php
> 30daysOFcode_Php

- 30daysOFcode_C++/day2.cpp
There was no need for typecasting so I updated the code and also added comments for the viewer to understand better.
> Add comments and update code for Day2 in C++

- 30daysOFcode_Go/day_12.go
added solution for day 12 in Golang.
> added day_12.go

- 30daysOFcode_Python/day21.py
> Created day21.py

- 30daysOFcode_TypeScript/day5.ts
- 30daysOFcode_TypeScript/day6.ts
added day5(Loops) in typescript
> added day5 in typescript

- 30daysOFcode_C++/day18.cpp
Properly formatted day18 problem in 30 days of code C++
> Updated day18

- 30daysOFcode_C++/day23.cpp
I've added the main function code and also added comments for better understanding and made some modifications too. Kindly review and merge my PR.
> Add driver code and comments

- 30daysOFcode_Php/day16.php
- 30daysOFcode_Php/day17.php
- 30daysOFcode_Php/day18.php
I have written the php codes for day 16, 17 and 18.
> Created Php files

- 30daysOFcode_JavaScript/README.md
- 30daysOFcode_JavaScript/day_6-Lets_Review.js
- 30daysOFcode_JavaScript/day_7-Arrays.js
- 30daysOFcode_JavaScript/day_9-Recursion.js
- 30daysOFcode_JavaScript/tests/day_6-Lets_Review.test.js
- 30daysOFcode_JavaScript/tests/day_7-Arrays.test.js
- 30daysOFcode_JavaScript/tests/day_9-Recursion.test.js
ref: #201 
This PR contains a few more test case additions to JS problems.
Improved logic of few recursion questions - earlier iterative approach was being used.
Kindly merge.
Thanks
> Testing javascript solutions

- 30daysOFcode_Dart/day0.dart
will add all solution in dart language
> added dart language

- 30daysOFcode_Go/solution_set2/day0.go
- 30daysOFcode_Go/solution_set2/day1.go
- 30daysOFcode_Go/solution_set2/day2.go
- 30daysOFcode_Go/solution_set2/day3.go
- 30daysOFcode_Go/solution_set2/day4.go
- 30daysOFcode_Go/solution_set2/day5.go
- 30daysOFcode_Go/solution_set2/day6.go
- created a folder in 30daysOFcode_Go/ called solution_set2/
- added day0-6 solutions
Solutions contains comments to help understand the code and Golang bit better, rest of the solution i will add soon
> added day0-6 solution in Golang

- 30daysOFcode_C/day12.c
- 30daysOFcode_C/day14.c
I checked Solutions table from your readme.md.
and I found that there's no solution for day12 / day14, so I tried to solve them.
> Added day12, day14 in C

- 30daysOFcode_C/Day 18 Stacks.C
- 30daysOFcode_C/Day 18 queue.C
Solved Day 18 problem using c program. Stacks and queues. #263
> Added day 18 files for c programing stacks and qeues

- 30daysOFcode_Php/day19.php
> Added day19.php

- 30daysOFcode_Php/day20.php
> Added day20.php

- 30daysOFcode_Scala/day0.scala
- 30daysOFcode_Scala/day1.scala
- 30daysOFcode_Scala/day2.scala
- 30daysOFcode_Scala/day3.scala
I have closed my previous PR. Kindly review this.
> Added Day0.scala, Day1.scala, Day2.scala, Day3.scala

- 30daysOFcode_Swift/Day7.swift
simple execution of arrays in the "swift" programming language
> Day7.swift

- 30daysOFcode_JavaScript/day 03.js
Hello, I just add comments on day 03, Please kindly check my pr issues #375. Thank you.
> Add explanation comments to day 03 on 30daysOFcode_Javascript

- 30daysOFcode_Java/day 26.java
Earlier there was a great difficulty in understanding day 26.java
Now after adding multiline comments it becomes easier.
Statements instructing the user to enter the specific value of variable also added
> User input and multiline comment added 

- 30daysOFcode_JavaScript/day 09.js
Hello, I just finished adding an explanation comments on 30daysOFcode_Javascript day 09. Please kindly check. Thank you.
> Add explanation comments on 30daysOFcode_Javascript day 09

- 30daysOFcode_C++/day 24.cpp
Hey, I've made some minor changes to the code and added comments for better readability. Kindly merge my PR.
> update code and add comments

- 30daysOFcode_Java/day 24.java
Day 24 More Linked Lists Java broken code added
#438 fixed
Online playground is working here,
[https://onlinegdb.com/rk6t4tnUP](https://onlinegdb.com/rk6t4tnUP)
> Day 24 More Linked Lists Java broken code added

- 30daysOFcode_Dart/day 04.dart
> added day04

- 30daysOFcode_Rust/day 07.rs
> Create day 07.rs

- 30daysOFcode_Rust/day 11.rs
> Create day 11.rs

- 30daysOFcode_Rust/day 12.rs
> Create day 12.rs

- 30daysOFcode_C++/day 28.cpp
I have added comments for day 28 program in c++. Kindly merge my pr for hactoberfest
> add comments

- 30daysOFcode_C++/day 11.cpp
The previous code wasn't giving the expected results. The logic was correct but somehow the execution was failing.
> Update day 11.cpp

- 30daysOFcode_C++/day 03.cpp
- 30daysOFcode_Python/day 03.py
I have just make a change on day-03 with my solution code. it can be run in any language but for now, I have just made changes in C++ and Python.
> CODE changed Day-03
